version: '3'
services:
  client:
    build: Azure.SignalR.Client
    ports:
      - "4200:80"
  server:
    build: Azure.SignalR.Server
    ports:
      - "5000:80"
  server2:
    image: azure-signalr_server:latest
    depends_on: 
      - server
    ports:
      - "5001:80"